backend:
  name: github
  repo: jordanlesich/techsage-blog

media_folder: /content/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: path, label: Path }
      - { name: subject, label: Subject, widget: select, options: ["Sagacity", "Creations", "Code", "Wellness", "Profiles", "Personal"]}
      - { name: body, label: Body, widget: markdown }
      - { name: header-image, label: Top Image, widget: image}
